### PR TITLE
Batch queries

### PR DESCRIPTION
**Pull request by jawj**
This PR adds support for batched queries/non-interactive transactions over http.

### CODE REVIEW

**Review by conradludgate — APPROVED** [review]

**Comment by nicksrandall** [comment]
Nice work @jawj. I see that you opted to make the transaction API a callback which then provides the same `sql` value that the user already has. I'm curious what the rationale was there. At first glance, it seems like unnecessary indirection but I'm sure I'm just missing something.

**Comment by jawj** [comment]
@nicksrandall Thanks Nick. You make a good point! I had two things in mind here:

1. You can't pass options to the query function inside a transaction, but it's tricky to express that restriction in the TypeScript types when you use the same function in both places.

For example, I've made this a runtime error, so it's nice that TypeScript also won't compile it:

```typescript
const [[r1], [r2]] = await sql.transaction(txn => [
  txn(SELECT 1, [], { arrayMode: true })
]);
```

It's quite possible I missed another way to do this, though.

2. It's potentially nice not to have to assign the query function to a variable before using it. With the pass-a-function design, you can do this:

```typescript
const [[r1], [r2]] = await neon(DATABASE_URL).transaction(txn => [
  txn`SELECT 1`,
  txn`SELECT 2`,
]);
```

Now, I think we could keep this design and, if and when we support interactive transactions, identify those as ones where the function is `async` i.e. it returns a Promise instead of an array.

On the other hand, I guess the DX there could be a bit confusing, since the two cases will look even more similar than in Prisma's design (and, of course, because it's different from Prisma).

It's a simple tweak to the code to make it work either way, but I've so far not tweaked the types to allow it.

I may need to ponder this for a bit. Comments welcome.

**Comment by jawj** [comment]
@nicksrandall OK, the code and types now allow for either an array or function argument to `transaction()`, and I think I'll document your array version as the standard approach.

Any options included in individual queries are now simply ignored, and TypeScript will catch it as a type error if you pass an `arrayMode` or `fullResults` value on the query that contradicts the transaction- or top-level options. I think that's probably good enough.

**Comment by shiyuhang0** [comment]
great work! This should be sufficient for most scenarios. As for the left scenarios, is there any possibility of providing interactive transactions over HTTP?

**Pull request merged**
